# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.CharField(blank=True, max_length=2000, null=True)),
                ('amount_paid', models.FloatField(default=0.0)),
                ('date_paid', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
