# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 20:37
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation_manager', '0002_auto_20160325_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owners_Points_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Travel_From', models.DateField(blank=True, null=True)),
                ('Expiration', models.DateField(blank=True, null=True)),
                ('Points_Description', models.CharField(blank=True, max_length=20, null=True)),
                ('Points_Available', models.IntegerField(blank=True, null=True)),
                ('Housekeeping_Available', models.IntegerField(blank=True, null=True)),
                ('fk_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='reservation_manager.Owner')),

            ],
        ),
    ]
