.TH "monthly_summary Directory Reference" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
monthly_summary Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBmigrations\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.ti -1c
.RI "file \fBadmin\&.py\fP"
.br
.ti -1c
.RI "file \fBmodels\&.py\fP"
.br
.ti -1c
.RI "file \fBtests\&.py\fP"
.br
.ti -1c
.RI "file \fBviews\&.py\fP"
.br
.in -1c
