.TH "reservation_manager/apps.py" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reservation_manager/apps.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBreservation_manager\&.apps\&.ReservationManagerConfig\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBreservation_manager\&.apps\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
