.TH "db_manager.views.DBManager" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
db_manager.views.DBManager \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBdumpData\fP"
.br
.ti -1c
.RI "def \fBviewUpdates\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file views\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def db_manager\&.views\&.DBManager\&.dumpData (request)"

.PP
Definition at line 7 of file views\&.py\&.
.SS "def db_manager\&.views\&.DBManager\&.viewUpdates (request)"

.PP
Definition at line 14 of file views\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
