.TH "dump_the_data" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dump_the_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBclean_app\fP = app\&.split('\&.')"
.br
.ti -1c
.RI "string \fBcmd\fP = 'python3 manage\&.py dumpdata {} --indent=4 > \&./fixtures/{}\&.json'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple dump_the_data\&.clean_app = app\&.split('\&.')"

.PP
Definition at line 5 of file dump_the_data\&.py\&.
.SS "string dump_the_data\&.cmd = 'python3 manage\&.py dumpdata {} --indent=4 > \&./fixtures/{}\&.json'"

.PP
Definition at line 6 of file dump_the_data\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
