.TH "dump_the_data.py" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dump_the_data.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBdump_the_data\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBdump_the_data\&.clean_app\fP = app\&.split('\&.')"
.br
.ti -1c
.RI "string \fBdump_the_data\&.cmd\fP = 'python3 manage\&.py dumpdata {} --indent=4 > \&./fixtures/{}\&.json'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
