.TH "guest_reservation_manager.views" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guest_reservation_manager.views \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBView\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmakeNewWish\fP"
.br
.ti -1c
.RI "def \fBget\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def guest_reservation_manager\&.views\&.get (request)"

.PP
Definition at line 21 of file views\&.py\&.
.SS "def guest_reservation_manager\&.views\&.makeNewWish (request)"

.PP
Definition at line 6 of file views\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
