.TH "guest_reservation_manager.migrations.0001_initial.Migration" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guest_reservation_manager.migrations.0001_initial.Migration \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Migration\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "list \fBdependencies\fP"
.br
.ti -1c
.RI "list \fBoperations\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file 0001_initial\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "list guest_reservation_manager\&.migrations\&.0001_initial\&.Migration\&.dependencies\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
1 = [
2     ]
.fi
.PP
Definition at line 9 of file 0001_initial\&.py\&.
.SS "list guest_reservation_manager\&.migrations\&.0001_initial\&.Migration\&.operations\fC [static]\fP"

.PP
Definition at line 12 of file 0001_initial\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
