.TH "guest_reservation_manager.apps.GuestReservationManagerConfig" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guest_reservation_manager.apps.GuestReservationManagerConfig \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits AppConfig\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP = 'guest_reservation_manager'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file apps\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "string guest_reservation_manager\&.apps\&.GuestReservationManagerConfig\&.name = 'guest_reservation_manager'\fC [static]\fP"

.PP
Definition at line 5 of file apps\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
