.TH "guest_reservation_manager.models.RuthSheet" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guest_reservation_manager.models.RuthSheet \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__str__\fP"
.br
.ti -1c
.RI "def \fB__unicode__\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBA_ResDate\fP = models\&.CharField( blank=True, null=True, max_length = 2000)"
.br
.ti -1c
.RI "tuple \fBB_UseDate\fP = models\&.CharField( blank=True, null=True, max_length = 2000)"
.br
.ti -1c
.RI "tuple \fBC_NTS\fP = models\&.CharField( blank=True, null=True, max_length = 2000)"
.br
.ti -1c
.RI "tuple \fBD_Resort\fP = models\&.CharField( blank=True, null=True, max_length = 2000)"
.br
.ti -1c
.RI "tuple \fBE_UnitSize\fP = models\&.CharField( blank=True, null=True, max_length = 2000)"
.br
.ti -1c
.RI "tuple \fBF_Slp\fP = models\&.CharField( blank=True, null=True, max_length = 2000)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file models\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def guest_reservation_manager\&.models\&.RuthSheet\&.__str__ (self)"

.PP
Definition at line 84 of file models\&.py\&.
.SS "def guest_reservation_manager\&.models\&.RuthSheet\&.__unicode__ (self)"

.PP
Definition at line 87 of file models\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "tuple guest_reservation_manager\&.models\&.RuthSheet\&.A_ResDate = models\&.CharField( blank=True, null=True, max_length = 2000)\fC [static]\fP"

.PP
Definition at line 77 of file models\&.py\&.
.SS "tuple guest_reservation_manager\&.models\&.RuthSheet\&.B_UseDate = models\&.CharField( blank=True, null=True, max_length = 2000)\fC [static]\fP"

.PP
Definition at line 78 of file models\&.py\&.
.SS "tuple guest_reservation_manager\&.models\&.RuthSheet\&.C_NTS = models\&.CharField( blank=True, null=True, max_length = 2000)\fC [static]\fP"

.PP
Definition at line 79 of file models\&.py\&.
.SS "tuple guest_reservation_manager\&.models\&.RuthSheet\&.D_Resort = models\&.CharField( blank=True, null=True, max_length = 2000)\fC [static]\fP"

.PP
Definition at line 80 of file models\&.py\&.
.SS "tuple guest_reservation_manager\&.models\&.RuthSheet\&.E_UnitSize = models\&.CharField( blank=True, null=True, max_length = 2000)\fC [static]\fP"

.PP
Definition at line 81 of file models\&.py\&.
.SS "tuple guest_reservation_manager\&.models\&.RuthSheet\&.F_Slp = models\&.CharField( blank=True, null=True, max_length = 2000)\fC [static]\fP"

.PP
Definition at line 82 of file models\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
