.TH "login.views" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
login.views \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBlogin_user\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def login\&.views\&.login_user (request)"

.PP
Definition at line 8 of file views\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
