.TH "monthly_summary.views.Report" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
monthly_summary.views.Report \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBremoveExcessSummaries\fP"
.br
.ti -1c
.RI "def \fBupdateSummaries\fP"
.br
.ti -1c
.RI "def \fBget\fP"
.br
.ti -1c
.RI "def \fBsavePayment\fP"
.br
.ti -1c
.RI "def \fBsetIsSavedForOwner\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file views\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def monthly_summary\&.views\&.Report\&.get (request, p_owner_username, p_year, p_month)"

.PP
Definition at line 92 of file views\&.py\&.
.SS "def monthly_summary\&.views\&.Report\&.removeExcessSummaries ()"

.PP
Definition at line 50 of file views\&.py\&.
.SS "def monthly_summary\&.views\&.Report\&.savePayment (request, p_check_number, p_amt_paid, p_monthly_summary)"

.PP
Definition at line 129 of file views\&.py\&.
.SS "def monthly_summary\&.views\&.Report\&.setIsSavedForOwner (request, reservation_id)"

.PP
Definition at line 140 of file views\&.py\&.
.SS "def monthly_summary\&.views\&.Report\&.updateSummaries ()"

.PP
Definition at line 58 of file views\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
