.TH "owners_point_manager.models.OwnerPointsManagerApplicationSettings" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
owners_point_manager.models.OwnerPointsManagerApplicationSettings \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBlast_updated\fP = models\&.DateTimeField(blank=True, null=True)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file models\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "tuple owners_point_manager\&.models\&.OwnerPointsManagerApplicationSettings\&.last_updated = models\&.DateTimeField(blank=True, null=True)\fC [static]\fP"

.PP
Definition at line 12 of file models\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
