.TH "owners_point_manager.models" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
owners_point_manager.models \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOwnerPointsManagerApplicationSettings\fP"
.br
.ti -1c
.RI "class \fBOwners_Points_Status\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBTRUE_OR_FALSE\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple owners_point_manager\&.models\&.TRUE_OR_FALSE"
\fBInitial value:\fP
.PP
.nf
1 = (
2     (1, "True"),
3     (0, "False")
4 )
.fi
.PP
Definition at line 5 of file models\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
