.TH "owners_point_manager.apps.OwnersPointManagerConfig" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
owners_point_manager.apps.OwnersPointManagerConfig \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits AppConfig\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP = 'owners_point_manager'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file apps\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "string owners_point_manager\&.apps\&.OwnersPointManagerConfig\&.name = 'owners_point_manager'\fC [static]\fP"

.PP
Definition at line 5 of file apps\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
