.TH "owners_point_manager.views.View" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
owners_point_manager.views.View \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBget\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 212 of file views\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def owners_point_manager\&.views\&.View\&.get (request)"

.PP
Definition at line 213 of file views\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
