.TH "push_backup" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
push_backup \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgetDateFolderName\fP"
.br
.ti -1c
.RI "def \fBgetBackupPath\fP"
.br
.ti -1c
.RI "def \fBmakeFolder\fP"
.br
.ti -1c
.RI "def \fBcopyJsonFiles\fP"
.br
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def push_backup\&.copyJsonFiles ()"

.PP
Definition at line 23 of file push_backup\&.py\&.
.SS "def push_backup\&.getBackupPath ()"

.PP
Definition at line 13 of file push_backup\&.py\&.
.SS "def push_backup\&.getDateFolderName ()"

.PP
Definition at line 6 of file push_backup\&.py\&.
.SS "def push_backup\&.main ()"

.PP
Definition at line 27 of file push_backup\&.py\&.
.SS "def push_backup\&.makeFolder ()"

.PP
Definition at line 18 of file push_backup\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
