.TH "push_backup.py" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
push_backup.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBpush_backup\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBpush_backup\&.getDateFolderName\fP"
.br
.ti -1c
.RI "def \fBpush_backup\&.getBackupPath\fP"
.br
.ti -1c
.RI "def \fBpush_backup\&.makeFolder\fP"
.br
.ti -1c
.RI "def \fBpush_backup\&.copyJsonFiles\fP"
.br
.ti -1c
.RI "def \fBpush_backup\&.main\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
