.TH "reservation_manager.views.Update" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reservation_manager.views.Update \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBupdateCanceled\fP"
.br
.ti -1c
.RI "def \fBget\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBupdate_in_progress\fP = False"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 184 of file views\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def reservation_manager\&.views\&.Update\&.get (request)"

.PP
Definition at line 207 of file views\&.py\&.
.SS "def reservation_manager\&.views\&.Update\&.updateCanceled ()"

.PP
Definition at line 190 of file views\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "reservation_manager\&.views\&.Update\&.update_in_progress = False\fC [static]\fP"

.PP
Definition at line 187 of file views\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
