.TH "reservation_manager.models.Owner" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reservation_manager.models.Owner \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Model\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__str__\fP"
.br
.ti -1c
.RI "def \fB__unicode__\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBemail\fP = models\&.EmailField( blank=True, null=True )"
.br
.ti -1c
.RI "tuple \fBusername\fP = models\&.CharField( max_length=2000)"
.br
.ti -1c
.RI "tuple \fBpassword\fP = models\&.CharField( max_length=2000)"
.br
.ti -1c
.RI "tuple \fBfirst_name\fP = models\&.CharField( blank=True, null=True, max_length=2000)"
.br
.ti -1c
.RI "tuple \fBlast_name\fP = models\&.CharField( blank=True, null=True, max_length=2000)"
.br
.ti -1c
.RI "tuple \fBphone_number\fP = models\&.CharField( blank=True, null=True, max_length=2000)"
.br
.ti -1c
.RI "tuple \fBowner_reimbursement_rate\fP = models\&.FloatField( blank=True, null=True )"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file models\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def reservation_manager\&.models\&.Owner\&.__str__ (self)"

.PP
Definition at line 29 of file models\&.py\&.
.SS "def reservation_manager\&.models\&.Owner\&.__unicode__ (self)"

.PP
Definition at line 32 of file models\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "tuple reservation_manager\&.models\&.Owner\&.email = models\&.EmailField( blank=True, null=True )\fC [static]\fP"

.PP
Definition at line 21 of file models\&.py\&.
.SS "tuple reservation_manager\&.models\&.Owner\&.first_name = models\&.CharField( blank=True, null=True, max_length=2000)\fC [static]\fP"

.PP
Definition at line 24 of file models\&.py\&.
.SS "tuple reservation_manager\&.models\&.Owner\&.last_name = models\&.CharField( blank=True, null=True, max_length=2000)\fC [static]\fP"

.PP
Definition at line 25 of file models\&.py\&.
.SS "tuple reservation_manager\&.models\&.Owner\&.owner_reimbursement_rate = models\&.FloatField( blank=True, null=True )\fC [static]\fP"

.PP
Definition at line 27 of file models\&.py\&.
.SS "tuple reservation_manager\&.models\&.Owner\&.password = models\&.CharField( max_length=2000)\fC [static]\fP"

.PP
Definition at line 23 of file models\&.py\&.
.SS "tuple reservation_manager\&.models\&.Owner\&.phone_number = models\&.CharField( blank=True, null=True, max_length=2000)\fC [static]\fP"

.PP
Definition at line 26 of file models\&.py\&.
.SS "tuple reservation_manager\&.models\&.Owner\&.username = models\&.CharField( max_length=2000)\fC [static]\fP"

.PP
Definition at line 22 of file models\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
