.TH "reservation_manager.models" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reservation_manager.models \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOwner\fP"
.br
.ti -1c
.RI "class \fBReservationManagerApplicationSettings\fP"
.br
.ti -1c
.RI "class \fBReservation\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBTRUE_OR_FALSE\fP"
.br
.ti -1c
.RI "tuple \fBREASON_ON_HOLD_CHOICES\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple reservation_manager\&.models\&.REASON_ON_HOLD_CHOICES"
\fBInitial value:\fP
.PP
.nf
1 = (
2     ("UPGD", "Needed For Upgrade"),
3     ("WSH","User requested this"),
4     ("OWN","Owner requested this"),
5     ("NH", "Not being held")
6 )
.fi
.PP
Definition at line 12 of file models\&.py\&.
.SS "tuple reservation_manager\&.models\&.TRUE_OR_FALSE"
\fBInitial value:\fP
.PP
.nf
1 = (
2     (1, "True"),
3     (0, "False")
4 )
.fi
.PP
Definition at line 7 of file models\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
