.TH "VacationScheduler/settings.py" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VacationScheduler/settings.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBVacationScheduler\&.settings\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBVacationScheduler\&.settings\&.BASE_DIR\fP = os\&.path\&.dirname(os\&.path\&.dirname(os\&.path\&.abspath(__file__)))"
.br
.ti -1c
.RI "string \fBVacationScheduler\&.settings\&.SECRET_KEY\fP = 'k$x%ggjn$x88$8s9d+b=@7qali&(h+c-ush)@g_y)7r4u+qg)v'"
.br
.ti -1c
.RI "\fBVacationScheduler\&.settings\&.DEBUG\fP = True"
.br
.ti -1c
.RI "list \fBVacationScheduler\&.settings\&.ALLOWED_HOSTS\fP = []"
.br
.ti -1c
.RI "list \fBVacationScheduler\&.settings\&.INSTALLED_APPS\fP"
.br
.ti -1c
.RI "list \fBVacationScheduler\&.settings\&.MIDDLEWARE_CLASSES\fP"
.br
.ti -1c
.RI "string \fBVacationScheduler\&.settings\&.ROOT_URLCONF\fP = 'VacationScheduler\&.urls'"
.br
.ti -1c
.RI "list \fBVacationScheduler\&.settings\&.TEMPLATES\fP"
.br
.ti -1c
.RI "string \fBVacationScheduler\&.settings\&.WSGI_APPLICATION\fP = '\fBVacationScheduler\&.wsgi\&.application\fP'"
.br
.ti -1c
.RI "dictionary \fBVacationScheduler\&.settings\&.DATABASES\fP"
.br
.ti -1c
.RI "list \fBVacationScheduler\&.settings\&.AUTH_PASSWORD_VALIDATORS\fP"
.br
.ti -1c
.RI "string \fBVacationScheduler\&.settings\&.LANGUAGE_CODE\fP = 'en-us'"
.br
.ti -1c
.RI "string \fBVacationScheduler\&.settings\&.TIME_ZONE\fP = 'America/New_York'"
.br
.ti -1c
.RI "\fBVacationScheduler\&.settings\&.USE_I18N\fP = True"
.br
.ti -1c
.RI "\fBVacationScheduler\&.settings\&.USE_L10N\fP = True"
.br
.ti -1c
.RI "\fBVacationScheduler\&.settings\&.USE_TZ\fP = True"
.br
.ti -1c
.RI "string \fBVacationScheduler\&.settings\&.STATIC_URL\fP = '/static/'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
