.TH "upgrade_recognition.views" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upgrade_recognition.views \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBprintLocationDictionary\fP"
.br
.ti -1c
.RI "def \fBgroupByNights\fP"
.br
.ti -1c
.RI "def \fBgroupByDate\fP"
.br
.ti -1c
.RI "def \fBgroupByLocation\fP"
.br
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def upgrade_recognition\&.views\&.groupByDate (reservation_array)"

.PP
Definition at line 32 of file views\&.py\&.
.SS "def upgrade_recognition\&.views\&.groupByLocation (request)"

.PP
Definition at line 55 of file views\&.py\&.
.SS "def upgrade_recognition\&.views\&.groupByNights (reservation_array)"

.PP
Definition at line 15 of file views\&.py\&.
.SS "def upgrade_recognition\&.views\&.main (request)"

.PP
Definition at line 80 of file views\&.py\&.
.SS "def upgrade_recognition\&.views\&.printLocationDictionary (dictionary)"

.PP
Definition at line 7 of file views\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
