.TH "VacationScheduler.custom_startup" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VacationScheduler.custom_startup \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsetUpToRunHourly\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def VacationScheduler\&.custom_startup\&.setUpToRunHourly ()"

.PP
Definition at line 3 of file custom_startup\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
