.TH "VacationScheduler.wsgi" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VacationScheduler.wsgi \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBapplication\fP = get_wsgi_application()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
WSGI config for VacationScheduler project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/howto/deployment/wsgi/

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "tuple VacationScheduler\&.wsgi\&.application = get_wsgi_application()"

.PP
Definition at line 16 of file wsgi\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
