.TH "upgrade_recognition/views.py" 3 "Fri Jul 8 2016" "WAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
upgrade_recognition/views.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBupgrade_recognition\&.views\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBupgrade_recognition\&.views\&.printLocationDictionary\fP"
.br
.ti -1c
.RI "def \fBupgrade_recognition\&.views\&.groupByNights\fP"
.br
.ti -1c
.RI "def \fBupgrade_recognition\&.views\&.groupByDate\fP"
.br
.ti -1c
.RI "def \fBupgrade_recognition\&.views\&.groupByLocation\fP"
.br
.ti -1c
.RI "def \fBupgrade_recognition\&.views\&.main\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WAM from the source code\&.
