# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('username', models.CharField(max_length=2000)),
                ('password', models.CharField(max_length=2000)),
                ('first_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('last_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=2000, null=True)),
                ('avail_points', models.IntegerField(blank=True)),
                ('owner_reimbursement_rate', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=2000, null=True)),
                ('date_of_reservation', models.DateField(blank=True)),
                ('number_of_nights', models.IntegerField(blank=True)),
                ('unit_size', models.CharField(blank=True, max_length=2000, null=True)),
                ('confirmation_number', models.CharField(max_length=2000)),
                ('points_required_for_reservation', models.IntegerField(blank=True)),
                ('is_buyer_lined_up', models.IntegerField(blank=True, choices=[(1, 'True'), (0, 'False')], null=True)),
                ('amount_paid', models.FloatField(blank=True)),
                ('date_booked', models.DateField(blank=True)),
                ('upgrade_status', models.CharField(blank=True, max_length=2000, null=True)),
                ('guest_certificate', models.CharField(blank=True, max_length=2000, null=True)),
                ('touched', models.DateField(blank=True)),
                ('fk_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_manager.Owner')),
            ],
        ),
    ]
