# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='avail_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_reimbursement_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='amount_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_booked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_of_reservation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_nights',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='points_required_for_reservation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='touched',
            field=models.DateField(blank=True, null=True),
        ),
    ]
